### ISSUE TITLE
Camera/FaceDetection not working on iOS devices 

### ISSUE THREAD

**Issue by MatejFacko** [lauirvin/react-use-face-detection#2]
**Packages used for development**

React - v18.1.0
Typescript - v4.6.4
React useFaceDetection - v1.0.1

**Mobile device:**
All iOS Devices

**Browser and version**
Google Chrome, Safari on iOS

Easy to  reproduce on live example: 
[https://serene-meerkat-95a23d.netlify.app/](url)

Seems like the camera can not be initialised or there is some problem with the camera stream.
(Sample is working on Android devices.)

**Comment by shubhamy-metricoidtech** [comment]
faced the same issue with chrome on android device loading stucks on true

**Comment by lauirvin** [comment]
Sorry for the late fix; please refer to this commit for the fix:
https://github.com/lauirvin/react-use-face-detection-demo/commit/d42d98f2fbf1f8349b11101e3e9745d219d833be

This has also been deployed to the live example. Thanks!
